### PR TITLE
Add South America Cities

### PR DESCRIPTION
**Pull request by wevertonj**
- Add Cities of Central America Islands.
- Add Cities of South America.
- Added cities translation file to pt_BR, but it doesn't work.

### CODE REVIEW

**Comment by Gedemon** [comment]
Thanks, but why the change to Oxford and Newcastle ?

Once merged I'll add the translation file in the .modinfo

**Comment by wevertonj** [comment]
Hi,

Sorry, I  forgot to revert this changes.
I seen that this names are in portuguese. In Brazilian portuguese Oxford and Newcastle aren't translated, but in Portugal portuguese are translated. As I do not what language is used as base, I decided revert this changes, but I forgot it.

**Comment by Gedemon** [comment]
Hello

Can you make another pull request without those two changes please ?

The city name ending with a Civilization tag are used in case that civilization found or capture the city on that plot, it's a "what if" option of the mod set in <En_US> langage by default (which is used in other translation if the tag are not set)

more info here: https://forums.civfanatics.com/threads/ynamp-sub-project-true-location-corresponding-city-names.605960/

**Comment by wevertonj** [comment]
yes, I can.

I make new pull request after I add more cities

**Pull request closed without merging**
